### ISSUE TITLE
Played MIDI not lining up with audio file

### ISSUE THREAD

**Issue by SuperMatCat24** [brainfoolong/gdscript-midi-parser#1]
When played together in a DAW, the midi and mp3 are perfectly lined up. However, when the midi is played through the plugin, it seems to be slower than expected and does not like up with the audio file. Also, when setting the audiostreamplayer's pitch scale to 0.94, it seems to line up almost perfectly

This is done using a modified version of the demo file. All that is changed is that it plays a different midi file and how note on/off is calculated.

[Midi Test Project.zip](https://github.com/brainfoolong/gdscript-midi-parser/files/14069255/Midi.Test.Project.zip)

**Comment by brainfoolong** [comment]
Hi. Thanks for the feedback. I've never actually measured the playback speed exactly. I've pushed an update which should fix the speed issue. However, in you example it's a little bit off anyway, because audio and midi player do not have same start points. But speed should be stable now.
